import type { SportHubConfig } from "@/lib/sport-hubs/types";
import type { SportId } from "@/lib/live-data";

export const SPORT_HUB_CONFIGS: Partial<Record<SportId, SportHubConfig>> = {
  basquete: {
    sportId: "basquete",
    layout: "team",
    eyebrow: "Central da NBA",
    title: "Basquete na LAP",
    subtitle: "Jogos da NBA, conferências, franquias, resultados e notícias em uma experiência feita para a temporada de basquete.",
    primaryCompetition: "NBA",
    eventPaths: ["basketball/nba"],
    standingsPath: "basketball/nba",
    rankingProvider: "standings",
    rankingTitle: "Conferências da NBA",
    rankingDescription: "Campanhas do Leste e do Oeste aparecem quando a classificação da temporada estiver disponível.",
    entityTitle: "Estrutura da temporada",
    entityDescription: "Os principais blocos que organizam o calendário da NBA.",
    entities: [
      { title: "Conferência Leste", category: "NBA", description: "Franquias do Atlântico, Central e Sudeste." },
      { title: "Conferência Oeste", category: "NBA", description: "Franquias do Noroeste, Pacífico e Sudoeste." },
      { title: "Temporada regular", category: "Calendário", description: "A fase longa que define campanha e posições." },
      { title: "Play-In", category: "Pós-temporada", description: "Disputa pelas últimas vagas de cada conferência." },
      { title: "Playoffs", category: "Pós-temporada", description: "Séries eliminatórias em melhor de sete." },
      { title: "NBA Finals", category: "Decisão", description: "Campeões de conferência disputam o título." },
    ],
    guide: [
      { title: "Quartos", value: "4 períodos", description: "O placar é dividido em quatro quartos, com prorrogação quando necessário." },
      { title: "Campanha", value: "V-D", description: "Vitórias, derrotas e aproveitamento organizam cada conferência." },
      { title: "Box score", value: "PTS · REB · AST", description: "Pontos, rebotes e assistências ajudam a ler o impacto dos jogadores." },
      { title: "Playoffs", value: "Melhor de 7", description: "Avança quem vencer quatro jogos na série." },
    ],
    emptyEventMessage: "A NBA está entre rodadas ou fora de temporada. Conferências, franquias e notícias continuam disponíveis.",
  },
  tenis: {
    sportId: "tenis",
    layout: "tour",
    eyebrow: "ATP, WTA e Grand Slams",
    title: "Tênis na LAP",
    subtitle: "Torneios, jogos, calendário e notícias dos circuitos masculino e feminino, com ranking apenas quando houver retorno confiável.",
    primaryCompetition: "ATP e WTA",
    eventPaths: ["tennis/atp", "tennis/wta"],
    rankingTitle: "Rankings ATP e WTA",
    rankingDescription: "A classificação só será exibida quando um retorno estruturado e atual estiver disponível.",
    entityTitle: "Circuitos e grandes torneios",
    entityDescription: "O mapa essencial da temporada internacional.",
    entities: [
      { title: "ATP Tour", category: "Circuito masculino", description: "Torneios do circuito profissional masculino." },
      { title: "WTA Tour", category: "Circuito feminino", description: "Torneios do circuito profissional feminino." },
      { title: "Australian Open", category: "Grand Slam", description: "Primeiro major do calendário." },
      { title: "Roland Garros", category: "Grand Slam", description: "Major disputado no saibro." },
      { title: "Wimbledon", category: "Grand Slam", description: "Major disputado na grama entre junho e julho." },
      { title: "US Open", category: "Grand Slam", description: "Major norte-americano em quadra dura." },
      { title: "Masters 1000", category: "ATP", description: "Torneios de maior peso abaixo dos Grand Slams." },
      { title: "WTA 1000", category: "WTA", description: "Eventos centrais da temporada feminina." },
    ],
    guide: [
      { title: "Sets", value: "2 ou 3", description: "A maioria dos jogos é melhor de três; alguns formatos masculinos usam melhor de cinco." },
      { title: "Chave", value: "Draw", description: "O chaveamento define confrontos e caminho até a final." },
      { title: "Superfície", value: "Dura · saibro · grama", description: "O piso altera velocidade, quique e estilo de jogo." },
      { title: "Ranking", value: "Pontos", description: "Resultados ao longo do calendário determinam a classificação." },
    ],
    spotlight: { title: "Wimbledon", text: "Wimbledon ocupa uma janela central do calendário entre junho e julho; jogos e notícias aparecem quando publicados." },
    emptyEventMessage: "Nenhum torneio com horário estruturado foi encontrado agora. O calendário e as notícias seguem ativos.",
  },
  golfe: {
    sportId: "golfe",
    layout: "tour",
    eyebrow: "PGA Tour e majors",
    title: "Golfe na LAP",
    subtitle: "Torneio atual, calendário, leaderboard e notícias do golfe profissional sem preencher lacunas com posições inventadas.",
    primaryCompetition: "PGA Tour",
    eventPaths: ["golf/pga"],
    rankingProvider: "golf-leaderboard",
    rankingTitle: "Leaderboard do torneio",
    rankingDescription: "Posições e scores entram somente durante torneios com leaderboard publicado.",
    entityTitle: "Circuito e majors",
    entityDescription: "Os eventos que organizam a temporada de golfe.",
    entities: [
      { title: "PGA Tour", category: "Circuito", description: "Principal circuito acompanhado inicialmente pela LAP." },
      { title: "FedExCup", category: "Temporada", description: "Sistema de pontos do calendário do PGA Tour." },
      { title: "Masters", category: "Major", description: "Major tradicional disputado em Augusta." },
      { title: "PGA Championship", category: "Major", description: "Um dos quatro principais torneios da temporada." },
      { title: "U.S. Open", category: "Major", description: "Major organizado pela USGA." },
      { title: "The Open", category: "Major", description: "Major histórico disputado em campos links." },
    ],
    guide: [
      { title: "Torneio", value: "Qui–dom", description: "Muitos eventos usam quatro rodadas entre quinta e domingo." },
      { title: "Par", value: "Referência", description: "Scores negativos indicam tacadas abaixo do par." },
      { title: "Corte", value: "Após 2 rodadas", description: "Parte do field avança para o fim de semana conforme o regulamento." },
      { title: "Leaderboard", value: "Posição", description: "Ordena os jogadores pelo score acumulado no torneio." },
    ],
    emptyEventMessage: "Nenhum torneio com dados de rodada foi encontrado agora. O guia do PGA Tour e as notícias continuam disponíveis.",
  },
  volei: {
    sportId: "volei",
    layout: "team",
    eyebrow: "Clubes, seleções e praia",
    title: "Vôlei na LAP",
    subtitle: "Superliga, seleções, Liga das Nações, Mundial de Clubes e vôlei de praia em uma central própria.",
    primaryCompetition: "Superliga e VNL",
    eventPaths: [],
    rankingTitle: "Classificações do vôlei",
    rankingDescription: "Tabelas entram quando uma integração estruturada de clubes e seleções estiver disponível.",
    entityTitle: "Competições para acompanhar",
    entityDescription: "A cobertura editorial continua útil mesmo entre rodadas.",
    entities: [
      { title: "Superliga Masculina", category: "Brasil", description: "Principal competição nacional masculina de clubes." },
      { title: "Superliga Feminina", category: "Brasil", description: "Principal competição nacional feminina de clubes." },
      { title: "Liga das Nações", category: "Seleções", description: "Temporada internacional anual de seleções." },
      { title: "Mundial de Clubes", category: "Clubes", description: "Encontro entre campeões e potências continentais." },
      { title: "Seleção Brasileira", category: "Seleções", description: "Calendário masculino e feminino do Brasil." },
      { title: "Vôlei de praia", category: "Praia", description: "Etapas por duplas em circuitos nacionais e internacionais." },
    ],
    guide: [
      { title: "Partida", value: "Melhor de 5", description: "Vence quem conquistar três sets." },
      { title: "Set", value: "25 pontos", description: "Os quatro primeiros sets normalmente vão a 25, com dois de vantagem." },
      { title: "Tie-break", value: "15 pontos", description: "O quinto set costuma ser disputado até 15, também com vantagem mínima." },
      { title: "Leitura", value: "Aces · bloqueios", description: "Saque, bloqueio, ataque e recepção ajudam a explicar o jogo." },
    ],
    emptyEventMessage: "A agenda estruturada de vôlei ainda está em expansão. Competições, formatos e notícias permanecem disponíveis.",
  },
  beisebol: {
    sportId: "beisebol",
    layout: "team",
    eyebrow: "Central da MLB",
    title: "Beisebol na LAP",
    subtitle: "Jogos da MLB, divisões, campanhas, resultados e notícias organizados inning por inning quando os dados estiverem disponíveis.",
    primaryCompetition: "MLB",
    eventPaths: ["baseball/mlb"],
    standingsPath: "baseball/mlb",
    rankingProvider: "standings",
    rankingTitle: "Divisões da MLB",
    rankingDescription: "Campanhas por divisão aparecem quando a classificação da temporada estiver publicada.",
    entityTitle: "Estrutura da MLB",
    entityDescription: "Ligas, divisões e caminho até a World Series.",
    entities: [
      { title: "American League", category: "Liga", description: "Leste, Central e Oeste da Liga Americana." },
      { title: "National League", category: "Liga", description: "Leste, Central e Oeste da Liga Nacional." },
      { title: "Temporada regular", category: "Calendário", description: "Séries frequentes ao longo da temporada." },
      { title: "Wild Card", category: "Pós-temporada", description: "Primeira etapa de acesso aos playoffs." },
      { title: "Championship Series", category: "Pós-temporada", description: "Decide o campeão de cada liga." },
      { title: "World Series", category: "Decisão", description: "Série que define o campeão da MLB." },
    ],
    guide: [
      { title: "Jogo", value: "9 innings", description: "Cada entrada tem ataque e defesa para os dois times." },
      { title: "Placar", value: "R · H · E", description: "Corridas, rebatidas e erros resumem a partida." },
      { title: "Pitching", value: "ERA · WHIP", description: "Métricas ajudam a ler o desempenho dos arremessadores." },
      { title: "Batting", value: "AVG · RBI · HR", description: "Média, corridas impulsionadas e home runs medem produção ofensiva." },
    ],
    emptyEventMessage: "Nenhum jogo da MLB foi encontrado no período atual. Divisões, formato e notícias continuam disponíveis.",
  },
  formula1: {
    sportId: "formula1",
    layout: "race",
    eyebrow: "Calendário de Grandes Prêmios",
    title: "Fórmula 1 na LAP",
    subtitle: "Treinos, classificação, sprint, corrida, pilotos e construtores organizados por fim de semana de Grande Prêmio.",
    primaryCompetition: "Fórmula 1",
    eventPaths: ["racing/f1"],
    standingsPath: "racing/f1",
    rankingProvider: "standings",
    rankingTitle: "Pilotos e construtores",
    rankingDescription: "As duas classificações aparecem quando a temporada publicar pontos estruturados.",
    entityTitle: "Fim de semana de GP",
    entityDescription: "As sessões que formam uma etapa da Fórmula 1.",
    entities: [
      { title: "Treinos livres", category: "Preparação", description: "Sessões para acerto do carro e coleta de dados." },
      { title: "Classificação", category: "Grid", description: "Define a ordem de largada da corrida principal." },
      { title: "Sprint", category: "Formato especial", description: "Corrida curta presente em etapas selecionadas." },
      { title: "Corrida", category: "Grande Prêmio", description: "Evento principal do fim de semana." },
      { title: "Pilotos", category: "Campeonato", description: "Pontos individuais ao longo da temporada." },
      { title: "Construtores", category: "Campeonato", description: "Soma de pontos das equipes." },
    ],
    guide: [
      { title: "Grid", value: "Classificação", description: "A sessão classificatória organiza as posições de largada." },
      { title: "Corrida", value: "Voltas", description: "Estratégia, pneus, pit stops e bandeiras definem o resultado." },
      { title: "Pontuação", value: "Pilotos e equipes", description: "Resultados alimentam os dois campeonatos da temporada." },
      { title: "Sprint", value: "Etapas selecionadas", description: "Alguns GPs incluem uma corrida curta adicional." },
    ],
    emptyEventMessage: "Nenhum Grande Prêmio está em andamento agora. O calendário da temporada e as classificações continuam disponíveis.",
  },
  mma: {
    sportId: "mma",
    layout: "combat",
    eyebrow: "Eventos e cards do UFC",
    title: "MMA na LAP",
    subtitle: "Próximos eventos, cards, categorias de peso, resultados e notícias do UFC sem rankings preenchidos manualmente.",
    primaryCompetition: "UFC",
    eventPaths: ["mma/ufc"],
    rankingTitle: "Rankings por categoria",
    rankingDescription: "Os rankings serão exibidos somente quando uma integração estruturada e atual estiver disponível.",
    entityTitle: "Categorias e card",
    entityDescription: "A estrutura básica para navegar em uma noite de lutas.",
    entities: [
      { title: "Card principal", category: "Evento", description: "Lutas de maior destaque da programação." },
      { title: "Preliminares", category: "Evento", description: "Lutas que antecedem o card principal." },
      { title: "Peso pesado", category: "Categoria", description: "Divisão de maior limite de peso." },
      { title: "Peso leve", category: "Categoria", description: "Uma das divisões mais profundas do UFC." },
      { title: "Peso pena", category: "Categoria", description: "Divisão entre o leve e o galo." },
      { title: "Peso galo", category: "Categoria", description: "Categoria presente nos rankings masculino e feminino." },
      { title: "Peso mosca", category: "Categoria", description: "Divisão de menor limite entre as principais categorias." },
      { title: "Peso palha", category: "Categoria", description: "Categoria feminina do UFC." },
    ],
    guide: [
      { title: "Luta comum", value: "3 rounds", description: "Combates regulares costumam ter três rounds." },
      { title: "Título ou principal", value: "5 rounds", description: "Disputas de cinturão e lutas principais podem ter cinco rounds." },
      { title: "Resultado", value: "KO · finalização · decisão", description: "O método e o tempo oficial explicam como a luta terminou." },
      { title: "Leitura", value: "Golpes · quedas", description: "Golpes significativos, quedas e controle ajudam a contar o combate." },
    ],
    emptyEventMessage: "Nenhum card estruturado foi encontrado agora. Categorias, formato e notícias continuam disponíveis.",
  },
  surfe: {
    sportId: "surfe",
    layout: "tour",
    eyebrow: "World Surf League",
    title: "Surfe na LAP",
    subtitle: "Etapas, baterias, janela de competição, ranking e notícias do circuito mundial em uma central própria.",
    primaryCompetition: "WSL Championship Tour",
    eventPaths: [],
    rankingTitle: "Ranking da WSL",
    rankingDescription: "A classificação aparece quando houver integração estruturada do circuito.",
    entityTitle: "Circuito e etapas",
    entityDescription: "Competições e conceitos que organizam a temporada de surfe.",
    entities: [
      { title: "Championship Tour", category: "WSL", description: "Circuito principal da elite mundial." },
      { title: "Challenger Series", category: "WSL", description: "Circuito de acesso ao Championship Tour." },
      { title: "Saquarema", category: "Etapa brasileira", description: "Parada importante do calendário no Brasil." },
      { title: "Pipeline", category: "Havaí", description: "Onda de referência do circuito internacional." },
      { title: "Teahupo'o", category: "Taiti", description: "Etapa conhecida por ondas tubulares de grande potência." },
      { title: "WSL Finals", category: "Decisão", description: "Evento que encerra a disputa pelo título conforme o formato da temporada." },
    ],
    guide: [
      { title: "Bateria", value: "Heat", description: "Surfistas disputam vagas dentro de uma janela de competição." },
      { title: "Somatório", value: "2 melhores ondas", description: "As duas maiores notas normalmente formam o total da bateria." },
      { title: "Prioridade", value: "Ordem de onda", description: "Define quem tem direito preferencial à próxima onda." },
      { title: "Janela", value: "Condições do mar", description: "A chamada depende de swell, vento e segurança." },
    ],
    emptyEventMessage: "Nenhuma bateria estruturada está disponível agora. O mapa do circuito e as notícias seguem ativos.",
  },
  rugby: {
    sportId: "rugby",
    layout: "team",
    eyebrow: "Seleções e clubes",
    title: "Rugby na LAP",
    subtitle: "Calendário, grandes torneios, seleções, clubes, formato e notícias em uma experiência própria da modalidade.",
    primaryCompetition: "Six Nations e Rugby Championship",
    eventPaths: [],
    rankingTitle: "Classificações do rugby",
    rankingDescription: "Tabelas e ranking entram quando houver integração estruturada para o torneio acompanhado.",
    entityTitle: "Torneios importantes",
    entityDescription: "Competições de seleções e clubes para orientar a navegação.",
    entities: [
      { title: "Six Nations", category: "Seleções", description: "Torneio anual entre seleções europeias." },
      { title: "Rugby Championship", category: "Seleções", description: "Torneio entre potências do hemisfério sul." },
      { title: "Copa do Mundo", category: "Seleções", description: "Principal competição internacional da modalidade." },
      { title: "Premiership", category: "Clubes", description: "Liga inglesa de clubes." },
      { title: "Top 14", category: "Clubes", description: "Principal liga francesa." },
      { title: "United Rugby Championship", category: "Clubes", description: "Competição multinacional de clubes." },
    ],
    guide: [
      { title: "Time", value: "XV", description: "O rugby union usa quinze jogadores titulares." },
      { title: "Try", value: "5 pontos", description: "A principal forma de pontuação abre chance para conversão." },
      { title: "Conversão", value: "2 pontos", description: "Chute após o try." },
      { title: "Penalty", value: "3 pontos", description: "Pode virar chute aos postes conforme a decisão da equipe." },
    ],
    emptyEventMessage: "A agenda estruturada de rugby ainda está em expansão. Torneios, formato e notícias continuam disponíveis.",
  },
  criquete: {
    sportId: "criquete",
    layout: "team",
    eyebrow: "Test, ODI e T20",
    title: "Críquete na LAP",
    subtitle: "Séries, formatos, innings, grandes competições e notícias organizados para quem acompanha ou está começando.",
    primaryCompetition: "Circuito internacional e IPL",
    eventPaths: [],
    rankingTitle: "Tabelas e rankings",
    rankingDescription: "Classificações entram quando houver integração estruturada para cada formato.",
    entityTitle: "Formatos e competições",
    entityDescription: "O críquete muda bastante conforme a duração da partida.",
    entities: [
      { title: "Test cricket", category: "Formato", description: "Partidas longas, com até cinco dias." },
      { title: "ODI", category: "Formato", description: "Formato internacional de cinquenta overs por lado." },
      { title: "T20", category: "Formato", description: "Formato curto de vinte overs por lado." },
      { title: "IPL", category: "Liga", description: "Liga de franquias no formato T20." },
      { title: "Cricket World Cup", category: "Seleções", description: "Principal torneio mundial no formato ODI." },
      { title: "T20 World Cup", category: "Seleções", description: "Copa do Mundo do formato curto." },
    ],
    guide: [
      { title: "Innings", value: "Entrada", description: "Período em que uma equipe rebate e a outra arremessa e defende." },
      { title: "Over", value: "6 bolas", description: "Unidade básica de arremessos válidos." },
      { title: "Wicket", value: "Eliminação", description: "A queda de wicket reduz as opções da equipe que rebate." },
      { title: "Run rate", value: "Ritmo", description: "Média de corridas por over ajuda a ler o andamento." },
    ],
    emptyEventMessage: "A agenda estruturada de críquete ainda está em expansão. Formatos, competições e notícias permanecem disponíveis.",
  },
  ciclismo: {
    sportId: "ciclismo",
    layout: "tour",
    eyebrow: "Provas e grandes voltas",
    title: "Ciclismo na LAP",
    subtitle: "Grandes voltas, clássicas, etapas, equipes e notícias organizadas para acompanhar a temporada de estrada.",
    primaryCompetition: "UCI WorldTour",
    eventPaths: [],
    rankingTitle: "Classificações da temporada",
    rankingDescription: "Ranking e resultados por etapa entram quando houver integração estruturada de prova.",
    entityTitle: "Calendário essencial",
    entityDescription: "Grandes voltas, clássicas e campeonatos de referência.",
    entities: [
      { title: "Tour de France", category: "Grande volta", description: "Prova por etapas disputada na França e países vizinhos." },
      { title: "Giro d'Italia", category: "Grande volta", description: "Grande volta italiana." },
      { title: "La Vuelta", category: "Grande volta", description: "Grande volta espanhola." },
      { title: "Clássicas", category: "Um dia", description: "Provas tradicionais disputadas em uma única jornada." },
      { title: "Mundial de Estrada", category: "Campeonato", description: "Disputa anual por seleções nacionais." },
      { title: "UCI WorldTour", category: "Circuito", description: "Calendário de elite do ciclismo de estrada." },
    ],
    guide: [
      { title: "Geral", value: "Menor tempo", description: "A classificação geral soma o tempo de todas as etapas." },
      { title: "Etapa", value: "Resultado do dia", description: "Cada jornada tem vencedor e perfil próprios." },
      { title: "Montanha", value: "Pontos", description: "Subidas categorizadas alimentam uma classificação específica." },
      { title: "Sprint", value: "Pontos", description: "Chegadas e metas intermediárias contam para a camisa de pontos." },
    ],
    emptyEventMessage: "A agenda estruturada de ciclismo ainda está em expansão. Grandes provas, formatos e notícias continuam disponíveis.",
  },
  natacao: {
    sportId: "natacao",
    layout: "event",
    eyebrow: "Provas, séries e finais",
    title: "Natação na LAP",
    subtitle: "Calendário de competições, provas, estilos, baterias e notícias em uma central preparada para tempos e resultados.",
    primaryCompetition: "Mundiais e grandes meetings",
    eventPaths: [],
    rankingTitle: "Tempos e classificações",
    rankingDescription: "Resultados e rankings entram somente quando houver retorno estruturado da competição.",
    entityTitle: "Provas e formatos",
    entityDescription: "O mapa básico para entender um programa de natação.",
    entities: [
      { title: "Livre", category: "Estilo", description: "Provas de velocidade, meio-fundo e fundo." },
      { title: "Costas", category: "Estilo", description: "Provas individuais disputadas de costas." },
      { title: "Peito", category: "Estilo", description: "Estilo com técnica e viradas específicas." },
      { title: "Borboleta", category: "Estilo", description: "Estilo potente com braçadas simultâneas." },
      { title: "Medley", category: "Combinado", description: "Reúne os quatro estilos em uma prova." },
      { title: "Revezamentos", category: "Equipe", description: "Provas por equipes em livre ou medley." },
    ],
    guide: [
      { title: "Bateria", value: "Série", description: "Atletas são distribuídos por raias em séries classificatórias." },
      { title: "Avanço", value: "Tempo", description: "Os melhores tempos seguem para semifinal ou final conforme a prova." },
      { title: "Split", value: "Parcial", description: "Tempos intermediários mostram a construção da prova." },
      { title: "Recorde", value: "Marca", description: "Recordes só são exibidos quando publicados pela competição." },
    ],
    emptyEventMessage: "Nenhuma prova estruturada está disponível agora. Estilos, formato e notícias seguem ativos.",
  },
  atletismo: {
    sportId: "atletismo",
    layout: "event",
    eyebrow: "Pista, campo e rua",
    title: "Atletismo na LAP",
    subtitle: "Meetings, provas, baterias, finais, marcas e notícias em uma central preparada para múltiplas disciplinas.",
    primaryCompetition: "Diamond League e campeonatos",
    eventPaths: [],
    rankingTitle: "Marcas e rankings",
    rankingDescription: "Classificações aparecem quando resultados estruturados e atuais estiverem disponíveis.",
    entityTitle: "Disciplinas para acompanhar",
    entityDescription: "Velocidade, resistência, saltos, lançamentos e provas combinadas.",
    entities: [
      { title: "Velocidade", category: "Pista", description: "100 m, 200 m, 400 m e revezamentos." },
      { title: "Meio-fundo e fundo", category: "Pista", description: "Do 800 m às provas longas de pista." },
      { title: "Barreiras", category: "Pista", description: "Provas com barreiras e obstáculos." },
      { title: "Saltos", category: "Campo", description: "Altura, vara, distância e triplo." },
      { title: "Lançamentos", category: "Campo", description: "Peso, disco, dardo e martelo." },
      { title: "Maratona", category: "Rua", description: "Prova de longa distância em percurso urbano." },
    ],
    guide: [
      { title: "Bateria", value: "Classificação", description: "Séries definem quem avança nas provas de pista." },
      { title: "Vento", value: "m/s", description: "A medição importa para validar marcas em algumas provas." },
      { title: "Tentativas", value: "Campo", description: "Saltos e lançamentos usam séries de tentativas." },
      { title: "Marca", value: "Tempo ou distância", description: "O critério muda conforme a disciplina." },
    ],
    emptyEventMessage: "Nenhuma prova estruturada está disponível agora. Disciplinas, formato e notícias continuam ativos.",
  },
  softball: {
    sportId: "softball",
    layout: "team",
    eyebrow: "Clubes, seleções e torneios",
    title: "Softball na LAP",
    subtitle: "Competições, formatos, seleções, calendário e notícias em uma central preparada para innings e resultados.",
    primaryCompetition: "Circuito internacional e universitário",
    eventPaths: [],
    rankingTitle: "Tabelas e classificações",
    rankingDescription: "Classificações entram quando houver integração estruturada da competição acompanhada.",
    entityTitle: "Cenários da modalidade",
    entityDescription: "Seleções, universidades e ligas que ajudam a orientar a cobertura.",
    entities: [
      { title: "Copa do Mundo", category: "Seleções", description: "Competição internacional por seleções." },
      { title: "Jogos Pan-Americanos", category: "Seleções", description: "Torneio relevante para países das Américas." },
      { title: "NCAA", category: "Universitário", description: "Temporada universitária dos Estados Unidos." },
      { title: "Liga japonesa", category: "Clubes", description: "Um dos centros tradicionais do softball de clubes." },
      { title: "Seleção Brasileira", category: "Brasil", description: "Calendário internacional do Brasil." },
      { title: "Softball feminino", category: "Elite", description: "Principal vertente competitiva internacional da modalidade." },
    ],
    guide: [
      { title: "Jogo", value: "7 innings", description: "Partidas normalmente usam sete entradas." },
      { title: "Placar", value: "R · H · E", description: "Corridas, rebatidas e erros resumem o jogo." },
      { title: "Pitching", value: "Arremesso", description: "O movimento e a distância diferem do beisebol." },
      { title: "Desempate", value: "Extra innings", description: "Entradas extras resolvem partidas empatadas." },
    ],
    emptyEventMessage: "A agenda estruturada de softball ainda está em expansão. Competições, formato e notícias permanecem disponíveis.",
  },
};

export function getSportHubConfig(sportId: SportId) {
  return SPORT_HUB_CONFIGS[sportId] ?? null;
}
